# Generated by Django 4.2.1 on 2023-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_task_user_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
